# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-tutorial-of-quantitative-trading
title: 量潮量化交易教程
author: 量潮科技
description: 量潮量化交易教程
# Jupyter Book Config
only_build_toc_files: true
